/**
 * Cultural Game Generator
 * Generates trivia cards, party games, conversation starters, quiz packs, bingo, and Would You Rather.
 * Uses GPT for content (questions/answers) and Flux for decorative card backgrounds.
 *
 * Fix: The game content generated by GPT is now actually overlaid on the PDF cards.
 * Previously, generateGameContent() was defined but never called during page generation.
 * Now each page generates its cards' content and stores it in metadata for PDF assembly.
 */
import { buildImagePrompt, generatePageImage, generateContent } from "./shared";
import { createJob, getJob, updateJob, addPageResult, type GenerationJob, type PageResult } from "../jobs";
import { assemblePdf, fetchImageBuffer, PageContent } from "../pdfAssembly";
import { storagePut } from "../storage";

export interface CulturalGameOptions {
  gameType: string;
  culturalEdition: string;
  occasion: string;
  cardCount: number;
  ageAppropriate: string;
}

const CARDS_PER_PAGE = 4; // 2x2 grid on 8.5x11

// Card grid layout constants for 8.5x11 (612x792 pt)
const PAGE_WIDTH = 612;
const PAGE_HEIGHT = 792;
const CARD_MARGIN = 20;
const CARD_GAP = 10;
const CARD_WIDTH = (PAGE_WIDTH - 2 * CARD_MARGIN - CARD_GAP) / 2;
const CARD_HEIGHT = (PAGE_HEIGHT - 2 * CARD_MARGIN - CARD_GAP) / 2;

interface GameCard {
  question: string;
  answer?: string;
  category?: string;
}

/**
 * Generate game card content using GPT, explicitly passing the user's selections.
 */
async function generateGameContent(
  opts: CulturalGameOptions,
  batchStart: number,
  batchSize: number
): Promise<GameCard[]> {
  const systemPrompt = `You are an expert game designer specializing in culturally authentic educational games.
Generate engaging, accurate, and respectful content for a ${opts.gameType} game.
Cultural edition: ${opts.culturalEdition}
Occasion: ${opts.occasion}
Age appropriateness: ${opts.ageAppropriate}
IMPORTANT: All content must be factually accurate, culturally respectful, and age-appropriate.
All questions and answers MUST be specifically about ${opts.culturalEdition} culture, traditions, history, food, music, or customs.
Do NOT generate generic questions — every card must be directly relevant to ${opts.culturalEdition}.`;

  const userPrompt = `Generate exactly ${batchSize} ${opts.gameType} cards (numbered ${batchStart + 1} to ${batchStart + batchSize}).
Theme: ${opts.culturalEdition} ${opts.gameType} for ${opts.occasion}
Audience: ${opts.ageAppropriate}

Each card needs:
- A question or prompt specifically about ${opts.culturalEdition} culture
- An answer (for trivia/quiz) or response option
- A category label (e.g., "Food", "Music", "History", "Traditions", "Language")

Return a JSON object with a "cards" array:
{"cards": [{"question": "...", "answer": "...", "category": "..."}]}

Make them engaging, educational, and 100% culturally authentic for ${opts.culturalEdition}.
For ${opts.ageAppropriate} audience.`;

  const content = await generateContent({
    systemPrompt,
    userPrompt,
    responseFormat: { type: "json_object" },
  });

  try {
    const parsed = JSON.parse(content);
    const cards = Array.isArray(parsed) ? parsed : parsed.cards || parsed.questions || [];
    return cards.slice(0, batchSize);
  } catch {
    // Fallback: generate placeholder cards
    return Array.from({ length: batchSize }, (_, i) => ({
      question: `${opts.culturalEdition} ${opts.gameType} Question ${batchStart + i + 1}`,
      answer: "Answer here",
      category: opts.culturalEdition,
    }));
  }
}

/**
 * Generate one page of cultural game cards.
 * Generates both the decorative background image AND the card content text.
 */
async function generateCulturalGamePage(pageIndex: number, job: GenerationJob): Promise<PageResult> {
  const opts = job.options as CulturalGameOptions;
  const batchStart = pageIndex * CARDS_PER_PAGE;
  const cardsOnThisPage = Math.min(CARDS_PER_PAGE, opts.cardCount - batchStart);

  // Step 1: Generate GPT content for this page's cards
  const cards = await generateGameContent(opts, batchStart, cardsOnThisPage);

  // Step 2: Generate the decorative background image for this page
  const bgPrompt = buildImagePrompt({
    subject: `decorative card background pattern with ornamental border design suitable for a ${opts.gameType} game card`,
    culturalVariant: opts.culturalEdition,
    additionalDetails: `elegant repeating pattern, rich colors, ${opts.occasion} themed, suitable as a card back or decorative frame, the card content area in the center must be light/white so text is readable`,
  });

  const { imageUrl } = await generatePageImage(bgPrompt);

  return {
    pageNumber: pageIndex + 1,
    imageUrl,
    status: "success",
    metadata: { cards, cardsOnThisPage },
  };
}

/**
 * Custom chunk processor that generates content + assembles PDF with card text overlay.
 */
async function processCulturalGameChunkInternal(job: GenerationJob): Promise<void> {
  const PAGES_PER_CHUNK = 3;
  const startIndex = job.nextPageIndex;
  const endIndex = Math.min(startIndex + PAGES_PER_CHUNK, job.totalPages);

  updateJob(job.id, {
    status: "generating",
    statusMessage: `Generating game cards ${startIndex * CARDS_PER_PAGE + 1}-${Math.min(endIndex * CARDS_PER_PAGE, (job.options as CulturalGameOptions).cardCount)} of ${(job.options as CulturalGameOptions).cardCount}...`,
  });

  for (let i = startIndex; i < endIndex; i++) {
    try {
      const result = await generateCulturalGamePage(i, job);
      addPageResult(job.id, result);
      updateJob(job.id, {
        nextPageIndex: i + 1,
        statusMessage: `Generated page ${i + 1} of ${job.totalPages}`,
      });
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : "Unknown error";
      addPageResult(job.id, {
        pageNumber: i + 1,
        imageUrl: "",
        status: "error",
        error: errorMsg,
      });
      updateJob(job.id, { nextPageIndex: i + 1 });
    }
  }

  const updatedJob = getJob(job.id);
  if (updatedJob && updatedJob.nextPageIndex >= updatedJob.totalPages) {
    await finalizeCulturalGamePdf(updatedJob);
  }
}

/**
 * Assemble the cultural game PDF with card content overlaid in a 2x2 grid.
 */
async function finalizeCulturalGamePdf(job: GenerationJob): Promise<void> {
  updateJob(job.id, { statusMessage: "Assembling PDF with game cards..." });

  const successPages = job.pageResults.filter(r => r.status === "success");

  if (successPages.length === 0) {
    updateJob(job.id, {
      status: "error",
      errorMessage: "No pages were generated successfully.",
    });
    return;
  }

  try {
    // Card positions in a 2x2 grid
    const cardPositions = [
      { col: 0, row: 0 },
      { col: 1, row: 0 },
      { col: 0, row: 1 },
      { col: 1, row: 1 },
    ];

    const pageContents: PageContent[] = [];

    for (const page of successPages) {
      const buffer = await fetchImageBuffer(page.imageUrl);
      const cards: GameCard[] = page.metadata?.cards || [];
      const cardsOnThisPage: number = page.metadata?.cardsOnThisPage || cards.length;

      // Build card layout with text overlay
      const cardLayouts: NonNullable<PageContent["cards"]> = [];

      for (let i = 0; i < cardsOnThisPage; i++) {
        const card = cards[i];
        if (!card) continue;

        const pos = cardPositions[i];
        const x = CARD_MARGIN + pos.col * (CARD_WIDTH + CARD_GAP);
        const y = CARD_MARGIN + pos.row * (CARD_HEIGHT + CARD_GAP);

        // Format card text: category at top, question in middle, answer at bottom
        const topText = card.category ? `[${card.category}]` : "";
        const frontText = card.question || "";
        const bottomText = card.answer ? `A: ${card.answer}` : "";

        cardLayouts.push({
          x,
          y,
          width: CARD_WIDTH,
          height: CARD_HEIGHT,
          imageBuffer: buffer, // use the decorative background for each card
          topText,
          frontText,
          bottomText,
          fontSize: 11,
        });
      }

      pageContents.push({
        cards: cardLayouts,
        showCutLines: true,
        pageNumber: page.pageNumber,
        totalPages: job.totalPages,
      });
    }

    const pdfBuffer = await assemblePdf(pageContents);

    const { url: pdfUrl } = await storagePut(
      `products/${job.generatorType}/${job.filename}`,
      pdfBuffer,
      "application/pdf"
    );

    const coverUrl = successPages[0]?.imageUrl || null;

    updateJob(job.id, {
      status: successPages.length === job.totalPages ? "complete" : "partial",
      pdfUrl,
      coverImageUrl: coverUrl,
      statusMessage: "PDF ready for download!",
    });
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : "PDF assembly failed";
    updateJob(job.id, {
      status: "error",
      errorMessage: errorMsg,
    });
  }
}

export function createCulturalGameJob(options: CulturalGameOptions): string {
  const totalPages = Math.ceil(options.cardCount / CARDS_PER_PAGE);
  const job = createJob(
    "cultural-game",
    totalPages,
    options,
    `cultural-game-${options.gameType.toLowerCase().replace(/\s+/g, "-")}.pdf`
  );
  return job.id;
}

export async function processCulturalGameChunk(jobId: string): Promise<void> {
  const job = getJob(jobId);
  if (!job) throw new Error("Job not found");
  await processCulturalGameChunkInternal(job);
}
