/**
 * PDF Assembly utility for creating print-ready PDFs.
 * All text (titles, instructions, labels, page numbers, branding) is overlaid
 * programmatically using real fonts — NEVER generated by AI.
 * 
 * Output: 8.5x11 inches (612x792 points at 72 DPI)
 */
import PDFDocument from "pdfkit";

const PAGE_WIDTH = 612;  // 8.5 inches at 72 DPI
const PAGE_HEIGHT = 792; // 11 inches at 72 DPI
const MARGIN = 36;       // 0.5 inch margins
const BRANDING_TEXT = "WishesWithoutBordersCo";

export interface PageContent {
  imageBuffer?: Buffer;
  imageUrl?: string;
  title?: string;
  subtitle?: string;
  instructions?: string[];
  labels?: Array<{ text: string; x: number; y: number; fontSize?: number }>;
  pageNumber?: number;
  totalPages?: number;
  // For card layouts (multiple cards per page)
  cards?: Array<{
    x: number;
    y: number;
    width: number;
    height: number;
    imageBuffer?: Buffer;
    frontText?: string;
    backText?: string;
    topText?: string;
    bottomText?: string;
    fontSize?: number;
  }>;
  // Custom content blocks
  contentBlocks?: Array<{
    text: string;
    x: number;
    y: number;
    width?: number;
    fontSize?: number;
    font?: string;
    align?: "left" | "center" | "right";
    color?: string;
  }>;
  // Whether to show cut lines (for cards/flashcards)
  showCutLines?: boolean;
  // Background color
  backgroundColor?: string;
}

export async function assemblePdf(pages: PageContent[]): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: [PAGE_WIDTH, PAGE_HEIGHT],
      margins: { top: 0, bottom: 0, left: 0, right: 0 },
      autoFirstPage: false,
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    for (const page of pages) {
      doc.addPage({ size: [PAGE_WIDTH, PAGE_HEIGHT], margins: { top: 0, bottom: 0, left: 0, right: 0 } });

      // Background color
      if (page.backgroundColor) {
        doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT).fill(page.backgroundColor);
      }

      // Full-page background image
      if (page.imageBuffer) {
        try {
          doc.image(page.imageBuffer, 0, 0, {
            width: PAGE_WIDTH,
            height: PAGE_HEIGHT,
          });
        } catch (e) {
          console.warn("Failed to embed image in PDF:", e);
        }
      }

      // Title
      if (page.title) {
        doc.font("Helvetica-Bold")
          .fontSize(18)
          .fillColor("#1a1a1a")
          .text(page.title, MARGIN, MARGIN, {
            width: PAGE_WIDTH - 2 * MARGIN,
            align: "center",
          });
      }

      // Subtitle
      if (page.subtitle) {
        doc.font("Helvetica")
          .fontSize(12)
          .fillColor("#444444")
          .text(page.subtitle, MARGIN, doc.y + 4, {
            width: PAGE_WIDTH - 2 * MARGIN,
            align: "center",
          });
      }

      // Instructions
      if (page.instructions && page.instructions.length > 0) {
        const instrY = page.title ? doc.y + 12 : MARGIN + 40;
        doc.font("Helvetica")
          .fontSize(11)
          .fillColor("#333333");
        for (const instruction of page.instructions) {
          doc.text(`• ${instruction}`, MARGIN + 10, instrY + (page.instructions.indexOf(instruction) * 16), {
            width: PAGE_WIDTH - 2 * MARGIN - 20,
          });
        }
      }

      // Custom labels at specific positions
      if (page.labels) {
        for (const label of page.labels) {
          doc.font("Helvetica")
            .fontSize(label.fontSize || 10)
            .fillColor("#333333")
            .text(label.text, label.x, label.y);
        }
      }

      // Content blocks
      if (page.contentBlocks) {
        for (const block of page.contentBlocks) {
          doc.font(block.font === "bold" ? "Helvetica-Bold" : "Helvetica")
            .fontSize(block.fontSize || 11)
            .fillColor(block.color || "#333333")
            .text(block.text, block.x, block.y, {
              width: block.width || PAGE_WIDTH - 2 * MARGIN,
              align: block.align || "left",
            });
        }
      }

      // Cards layout with cut lines
      if (page.cards) {
        for (const card of page.cards) {
          // Card image
          if (card.imageBuffer) {
            try {
              doc.image(card.imageBuffer, card.x, card.y, {
                width: card.width,
                height: card.height,
              });
            } catch (e) {
              // Fill with a light color if image fails
              doc.rect(card.x, card.y, card.width, card.height).fill("#f0f0f0");
            }
          }

          // Card text overlays
          if (card.topText) {
            doc.font("Helvetica-Bold")
              .fontSize(card.fontSize || 12)
              .fillColor("#1a1a1a")
              .text(card.topText, card.x + 4, card.y + 4, {
                width: card.width - 8,
                align: "center",
              });
          }
          if (card.bottomText) {
            doc.font("Helvetica")
              .fontSize((card.fontSize || 12) - 2)
              .fillColor("#333333")
              .text(card.bottomText, card.x + 4, card.y + card.height - 20, {
                width: card.width - 8,
                align: "center",
              });
          }
          if (card.frontText) {
            const textY = card.y + card.height / 2 - 10;
            doc.font("Helvetica-Bold")
              .fontSize(card.fontSize || 14)
              .fillColor("#1a1a1a")
              .text(card.frontText, card.x + 8, textY, {
                width: card.width - 16,
                align: "center",
              });
          }
        }

        // Cut lines
        if (page.showCutLines) {
          doc.strokeColor("#cccccc").lineWidth(0.5).dash(4, { space: 2 });
          // Draw cut lines between cards
          const uniqueXs = Array.from(new Set(page.cards.map(c => c.x))).sort((a, b) => a - b);
          const uniqueYs = Array.from(new Set(page.cards.map(c => c.y))).sort((a, b) => a - b);
          
          // Vertical cut lines
          for (const x of uniqueXs) {
            if (x > MARGIN) {
              doc.moveTo(x, MARGIN).lineTo(x, PAGE_HEIGHT - MARGIN).stroke();
            }
          }
          // Right edge of last column
          if (page.cards.length > 0) {
            const rightEdge = Math.max(...page.cards.map(c => c.x + c.width));
            if (rightEdge < PAGE_WIDTH - MARGIN) {
              doc.moveTo(rightEdge, MARGIN).lineTo(rightEdge, PAGE_HEIGHT - MARGIN).stroke();
            }
          }
          
          // Horizontal cut lines
          for (const y of uniqueYs) {
            if (y > MARGIN) {
              doc.moveTo(MARGIN, y).lineTo(PAGE_WIDTH - MARGIN, y).stroke();
            }
          }
          // Bottom edge of last row
          if (page.cards.length > 0) {
            const bottomEdge = Math.max(...page.cards.map(c => c.y + c.height));
            if (bottomEdge < PAGE_HEIGHT - MARGIN) {
              doc.moveTo(MARGIN, bottomEdge).lineTo(PAGE_WIDTH - MARGIN, bottomEdge).stroke();
            }
          }
          doc.undash();
        }
      }

      // Page number
      if (page.pageNumber) {
        const pageNumText = page.totalPages
          ? `${page.pageNumber} / ${page.totalPages}`
          : `${page.pageNumber}`;
        doc.font("Helvetica")
          .fontSize(9)
          .fillColor("#888888")
          .text(pageNumText, PAGE_WIDTH - MARGIN - 60, PAGE_HEIGHT - 24, {
            width: 60,
            align: "right",
          });
      }

      // Branding footer
      doc.font("Helvetica")
        .fontSize(7)
        .fillColor("#aaaaaa")
        .text(BRANDING_TEXT, MARGIN, PAGE_HEIGHT - 20, {
          width: PAGE_WIDTH - 2 * MARGIN - 70,
          align: "left",
        });
    }

    doc.end();
  });
}

/**
 * Fetches an image from a URL and returns it as a Buffer.
 */
export async function fetchImageBuffer(url: string): Promise<Buffer> {
  // Handle relative URLs (from our storage) - always resolve against localhost
  let fullUrl = url;
  if (url.startsWith("/")) {
    const port = process.env.PORT || 3000;
    fullUrl = `http://localhost:${port}${url}`;
  }
  
  const response = await fetch(fullUrl);
  if (!response.ok) {
    throw new Error(`Failed to fetch image: ${response.status} from ${fullUrl}`);
  }
  const arrayBuffer = await response.arrayBuffer();
  return Buffer.from(arrayBuffer);
}
